// ensure all headers are included just to test compilation

#include <ciri/gfx/BlendColorMask.hpp>
#include <ciri/gfx/BlendFunction.hpp>
#include <ciri/gfx/BlendMode.hpp>
#include <ciri/gfx/Camera.hpp>
#include <ciri/gfx/ClearFlags.hpp>
#include <ciri/gfx/CompareFunction.hpp>
#include <ciri/gfx/CullMode.hpp>
#include <ciri/gfx/FillMode.hpp>
#include <ciri/gfx/FPSCamera.hpp>
#include <ciri/gfx/GraphicsApiType.hpp>
#include <ciri/gfx/IBlendState.hpp>
#include <ciri/gfx/IConstantBuffer.hpp>
#include <ciri/gfx/IDepthStencilState.hpp>
#include <ciri/gfx/IGraphicsDevice.hpp>
#include <ciri/gfx/IIndexBuffer.hpp>
#include <ciri/gfx/IRasterizerState.hpp>
#include <ciri/gfx/IRenderTarget2D.hpp>
#include <ciri/gfx/ISamplerState.hpp>
#include <ciri/gfx/IShader.hpp>
#include <ciri/gfx/ITexture2D.hpp>
#include <ciri/gfx/ITextureCube.hpp>
#include <ciri/gfx/IVertexBuffer.hpp>
#include <ciri/gfx/MayaCamera.hpp>
#include <ciri/gfx/ObjModel.hpp>
#include <ciri/gfx/Plane.hpp>
#include <ciri/gfx/PrimitiveTopology.hpp>
#include <ciri/gfx/SamplerFilter.hpp>
#include <ciri/gfx/SamplerWrap.hpp>
#include <ciri/gfx/ShaderStage.hpp>
#include <ciri/gfx/StencilOperation.hpp>
#include <ciri/gfx/TextureFlags.hpp>
#include <ciri/gfx/TextureFormat.hpp>
#include <ciri/gfx/VertexDeclaration.hpp>
#include <ciri/gfx/VertexElement.hpp>
#include <ciri/gfx/VertexFormat.hpp>
#include <ciri/gfx/VertexUsage.hpp>